video/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from users.views import LoginView, RegisterView, LogoutView, IndexView, SearchView, InfoView, InfoFav, InfoMess, Detail, Comment, ActiveUser, ForgetPass, ResetPass, ChildCom
import xadmin

urlpatterns = [
    path('xadmin/', xadmin.site.urls),
    path('', IndexView.as_view(),name='index'),
    path('login/',LoginView.as_view(),name='login'),
    path('register/',RegisterView.as_view(),name='register'),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('captcha/',include('captcha.urls')),
    path('search/',SearchView.as_view(),name='search'),
    path('info/',InfoView.as_view(),name='info'),
    path('info_fav/',InfoFav.as_view(),name='info_fav'),
    path('message/',InfoMess.as_view(),name='info_mess'),
    path('detail/',Detail.as_view(),name='video_detail'),
    path('comment/',Comment.as_view(),name='comment'),
    path('active/',ActiveUser.as_view(),name='active_user'),
    path('forget/',ForgetPass.as_view(),name='forget_pass'),
    path('reset/',ResetPass.as_view(),name='reset_pass'),
    path('childcom/',ChildCom.as_view(),name='childcom'),

]

operation/models.py
from datetime import datetime

from django.db import models

from users.models import UserProfile
from videos.models import Video





class VideoComments(models.Model):
    '''视频评论'''
    user = models.ForeignKey(UserProfile,verbose_name='用户',on_delete=models.CASCADE)
    course = models.ForeignKey(Video,verbose_name='视频',on_delete=models.CASCADE)
    comments = models.CharField('评论',max_length=200)
    add_time = models.DateTimeField('添加时间', default=datetime.now)


    class Meta:
        verbose_name = '视频评论'
        verbose_name_plural = verbose_name


class UserFavorite(models.Model):
    user = models.ForeignKey(UserProfile,verbose_name='用户',on_delete=models.CASCADE)
    fav_id = models.IntegerField('数据id',default=0)
    add_time = models.DateTimeField('添加时间', default=datetime.now)

    class Meta:
        verbose_name = '用户收藏'
        verbose_name_plural = verbose_name


class ChildComment(models.Model):
    '''子评论'''
    user = models.ForeignKey(UserProfile, verbose_name='用户', on_delete=models.CASCADE)
    comments = models.CharField('评论', max_length=200)
    add_time = models.DateTimeField('添加时间', default=datetime.now)
    fa = models.ForeignKey(VideoComments, verbose_name='子评论', on_delete=models.CASCADE)

    class Meta:
        verbose_name = '视频评论'
        verbose_name_plural = verbose_name


class UserMessage(models.Model):
    user = models.IntegerField('接受用户',default=0)
    message = models.CharField('消息内容',max_length=500)
    has_read = models.BooleanField('是否已读',default=False)
    add_time = models.DateTimeField('添加时间', default=datetime.now)

    class Meta:
        verbose_name = '用户消息'
        verbose_name_plural = verbose_name

xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getfullargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.urls.base import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass


def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)


def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getfullargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):

    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user,
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user

        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <title>看电影</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/4.1.0/css/bootstrap.min.css">
  <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://cdn.bootcss.com/popper.js/1.12.5/umd/popper.min.js"></script>
  <script src="https://cdn.bootcss.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
  <link href="http://cdn.bootcss.com/video.js/6.0.0-RC.5/alt/video-js-cdn.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.css">
  <style type="text/css">
p {
    white-space:nowrap;
    overflow:hidden;
    text-overflow:clip;
    width:100%;
}
</style>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-4791633031397452",
    enable_page_level_ads: true
  });
</script>
</head>
<body >

 <!-- 顶部栏 -->   
<div class="container-fluid bg-dark">
    <div class="container">
<nav class="navbar navbar-expand-lg navbar-dark ">
    <a class="navbar-brand" href="/">Movie</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav mr-auto">
{#        <li class="nav-item active">#}
{#          <a class="nav-link" href="/">主页<span class="sr-only">(current)</span></a>#}
{#        </li>#}
{#        <li class="nav-item">#}
{#          <a class="nav-link" href="#">字幕</a>#}
{#        </li>#}
{#        <li class="nav-item">#}
{#          <a class="nav-link" href="#">历史</a>#}
{#        </li>#}
{#        <li class="nav-item">#}
{#          <a class="nav-link" href="#">用户</a>#}
{#        </li>#}
      </ul>
      <!-- <a href="https:www.baidu.com"><i class="fa fa-user" style="font-size:24px;color:white"></i></a> -->
      {% if request.user.is_authenticated %}
      <a href="/info/" class="btn btn-info" role="button">用户信息</a>
      <span>&nbsp</span>
      <a href="/logout/" class="btn btn-info" role="button">登出</a>
      {% else %}
      <a href="/register/" class="btn btn-info" role="button">注册</a>
      <span>&nbsp</span>
      <a href="/login/" class="btn btn-info" role="button">登录</a>
      <span>&nbsp</span>
      <a href="/forget/" class="btn btn-info" role="button">忘记密码</a>
      {% endif %}
    </div>
  </nav>
</div>
</div>
{% block mainbody %}
{% endblock %}
</body>
</html>

templates/detail.html
{% extends "base.html" %}

{% block mainbody %}
<div class="container mt-5">
    <div class="row">
         <!-- 左边栏 -->
          <!-- 视频栏 -->
                <div class="col-sm-10">
{#                <video class="img-fluid" controls>#}
{#                  <source src="{{ video.video_url }}" type="video/mp4">#}
{#                </video>#}
                <div>
                <video id="hls-video"   style="width: 100%" class="video-js vjs-default-skin" controls preload="none" data-setup='{ "aspectRatio":"640:267", "playbackRates": [1, 1.5, 2] }'>
                <!-- 直播的视频源 -->
                <source src="{{ video.video_url }}" type="application/x-mpegURL">
                <!-- 点播的视频源 -->
                <!--<source src="http://devstreaming.apple.com/videos/wwdc/2015/413eflf3lrh1tyo/413/hls_vod_mvp.m3u8" type="application/x-mpegURL">-->
                </video>

                </div>
                <!-- 详情栏 -->
                <div class="card mt-5">
                                <div class="card-body">
                                  <h4 class="card-title">{{ video.name }}</h4>
                                  <div class="card-text mb-3">{{ video.desc|safe}}</div>
{#                                  <a href="#" class="card-link">Card link</a>#}
{#                                  <a href="#" class="card-link">Another link</a>#}
                                </div>
                </div>
                 <!-- 写评论栏 -->
                {% if request.user.is_authenticated %}
                 <div class=" mt-5">
                        <h3 class="mb-3">评论</h3>
                     <form action="/comment/?video_id={{ video.id }}" method="POST" autocomplete="off">
                        <div class="input-group mb-3">
                          <input name="comment" type="text" class="form-control" placeholder="评论">
                          <div class="input-group-append">
                            <button class="btn btn-success" type="submit">发射</button>
                           </div>
                        </div>
                         {% csrf_token %}
                     </form>
                </div>
                {% else %}
                <div class=" mt-5">
                        <h3 class="mb-3">评论</h3>
                         <div class="badge badge-secondary mb-2" style="float: right;">请登录以后评论</div>
                        <div class="input-group mb-3 ">
                          <input type="text" class="form-control" placeholder="姓名">
                        </div>

                        <div class="input-group mb-3 ">
                          <input type="text" class="form-control" placeholder="邮箱">
                        </div>

                        <div class="input-group mb-3 ">
                          <input type="text" class="form-control" placeholder="评论">
                          <div class="input-group-append">
                            <button class="btn btn-success disabled" type="submit">发射</button>
                           </div>
                        </div>
                </div>
                {% csrf_token %}
                {% endif %}
                 <!-- 展示评论栏 -->
                <div class=" mt-5">



                        <div>
                  <ul class="list-group">
                      {% for comment in comments %}
                      <li  class="list-group-item">
                          <a><img src="https://tva2.sinaimg.cn/crop.0.1.635.635.50/62d8efadgw1ej30downrsj20hs0hq0ws.jpg" width='40' height='40'></a>
                          <a href="#" class="ml-3 btn btn-link">{{ comment.user }}</a><span class="badge badge-pill badge-info" style="float: right;">{{ comment.add_time }}</span>
                          <div class="ml-5 mt-3">{{ comment.comments }}</div>

                            <div class=" mt-5">

                     <form action="/childcom/?comment_id={{ comment.id }}&video_id={{ video.id }}" method="POST" autocomplete="off">
                        <div class="input-group mb-3">
                          <input name="comment" type="text" class="form-control" placeholder="回复">
                          <div class="input-group-append">
                            <button class="btn btn-success" type="submit">发射</button>
                           </div>
                        </div>
                         {% csrf_token %}
                     </form>
                </div>
                      </li>
                          {% for child in comment.childcomment_set.all %}
                      <li  class="list-group-item ml-5">

                          <a><img src="https://tva2.sinaimg.cn/crop.0.1.635.635.50/62d8efadgw1ej30downrsj20hs0hq0ws.jpg" width='40' height='40'></a>
                          <a href="#" class="ml-3 btn btn-link">{{ child.user }}</a><span class="badge badge-pill badge-info" style="float: right;">{{ child.add_time }}</span>
                          <div class="ml-5 mt-3">{{ child.comments }}</div>

                      </li>
                      {% endfor %}
                      {% endfor %}
                  </ul>
                </div>





                </div>

                </div>

                 <!-- 右边栏 -->
                  <!-- 推荐栏 -->
{#                <div class="col-sm-2">#}
{#                        <div>#}
{#                                <a href="">#}
{#                                <img class="img-fluid" src="http://pianyuan.net/Uploads/Picture/litpic/06/25Jun2018202006.jpg">#}
{#                                </a>#}
{#                            </div>#}
{#                            <div>#}
{#                                <div class="border">&nbsp;</div>#}
{#                                <a href="https://www.baidu.com">电影</a>#}
{#                                <p>主演</p>#}
{#                        </div>#}
{#                </div>#}
    </div>
</div>
<script src="http://cdn.bootcss.com/video.js/6.0.0-RC.5/video.js"></script>
<!-- PC 端浏览器不支持播放 hls 文件(m3u8), 需要 videojs-contrib-hls 来给我们解码 -->
<script src="http://cdn.bootcss.com/videojs-contrib-hls/5.3.3/videojs-contrib-hls.js"></script>
<script>
    // XMLHttpRequest cannot load http://xxx/video.m3u8. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://192.168.198.98:8000' is therefore not allowed access.
    // 由于 videojs-contrib-hls 需要通过 XHR 来获取解析 m3u8 文件, 因此会遭遇跨域问题, 请设置浏览器运行跨域
    var player = videojs('hls-video');
    player.play();
</script>
{% endblock %}

templates/forget.html
{% extends "base.html" %}

{% block mainbody %}
         <!-- 内容栏 -->
         <div class="container mt-5">

            <div class="mx-auto" style="width: 300px;">
                <table class="table">
                    <tbody>
                        <tr>

                            <td>
                                <div class="my-5">
                                    <form action="/forget/" method="POST" autocomplete="off">
                                    <div class="input-group mb-3">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text" id="basic-addon1">
                                                    邮箱
                                                </span>
                                            </div>
                                            <input name="email" type="email" class="form-control" placeholder="邮箱" aria-label="邮箱"
                                            aria-describedby="basic-addon1">
                                            <div class="input-group-append">
                                            <button class="btn btn-success" style="float: right;" type="submit">
                                                    提交
                                                </button>
                                                </div>
                                        </div>

                                        {% if  msg %}

                                        <div class="alert alert-info">
                                            <strong>{{ msg }}</strong>
                                        </div>
                                        {% endif %}
                                        {% csrf_token %}
                                    </form>

                                </div>
                            </td>
                        </tr>
                </table>
            </div>
        </div>
{% endblock %}

templates/index.html
{% extends "base.html" %}
 
{% block mainbody %}


<div  style="background-image:url('http://p18.qhimg.com/bdr/__/d/_open360/design0403/24.jpg');height:150px;">
    <div class="container " >
    <div  style="float: right;margin-top:5rem;">
    <form action="/search/" method="POST" autocomplete="off" class="form-inline">
        <div class="input-group ">
        <input name="keywords" class="form-control" type="search" placeholder="搜索" aria-label="Search">
            <div class="input-group-append">
        <button class="btn btn-success" type="submit">搜索</button>
            </div>
        </div>
        {% csrf_token %}
  </form>
  </div>
  </div>
</div>

 <!-- 筛选栏 -->   
<div class="container mt-3" >
        <div>
            <p>资源分类：
                <a href="/?cate=" class="btn btn-outline-success btn-sm {% ifequal category_id '' %} active {% endifequal %}" role="button">不限</a>
                {% for category in all_categorys %}
                <a href="/?cate={{ category.id }}" class="btn btn-outline-success btn-sm {% ifequal category_id category.id|stringformat:"i" %} active {% endifequal %}" role="button">{{ category.cate }}</a>
                {% endfor %}
            </p>
        </div>
{#        <div>#}
{#            <p>资源分类：#}
{#                <a href="/?cate=&date={{ date_id }}" class="btn btn-outline-success btn-sm {% ifequal category_id '' %} active {% endifequal %}" role="button">不限</a>#}
{#                {% for category in all_categorys %}#}
{#                <a href="/?cate={{ category.id }}&date={{ date_id }}" class="btn btn-outline-success btn-sm {% ifequal category_id category.id|stringformat:"i" %} active {% endifequal %}" role="button">{{ category.cate }}</a>#}
{#                {% endfor %}#}
{#            </p>#}
{#        </div>#}

{#        <div>#}
{#                <p>上映年份：#}
{##}
{##}
{#                <a href="/?cate={{ category_id }}&date=" class="btn btn-outline-success btn-sm {% ifequal date_id '' %} active {% endifequal %}" role="button">不限</a>#}
{#                {% for date in all_date %}#}
{#                <a href="/?cate={{ category_id }}&date={{ date.id }}" class="btn btn-outline-success btn-sm {% ifequal date_id date.id|stringformat:"i" %} active {% endifequal %}" role="button">{{ date.date }}</a>#}
{#                {% endfor %}#}
{#                </p>#}
{#        </div>#}

</div>

 <!-- 内容栏 -->   
<div class="container mt-5">
    <div class="row">
    <div class="col-md-10">
    <div class="row">
    {% for video in all_videos %}
    <div class="col-sm-3 col-md-3 col-xs-4 col-lg-2">
            <div>
                <a href="/detail/?id={{ video.id }}">
                <img class="img-fluid" src="{{ video.image_url }}">
                </a>
            </div>
            <div>
                <p class="mt-3"><a data-toggle="tooltip" title="{{ video.name}}" href="/detail/?id={{ video.id }}">{{ video.name}}</a></p>
                <p data-toggle="tooltip" title="{{ video.actor}}">{{ video.actor}}</p>
            </div>
    </div>
    {% endfor %}


</div>
</div>
</div>


          
</div>
 <!-- 分页栏 -->   
<div class="container mt-5 ">
        <ul class="pagination justify-content-center">

  <!-- 如果当前页还有上一页，显示一个上一页的按钮 -->
  {% if all_videos.has_previous %}
      <li class="page-item"><a class="page-link" href="?page={{ all_videos.previous_page_number }}">上一页</a></li>
      <li class="page-item"><a class="page-link" href="?page={{ all_videos.previous_page_number }}" >{{ all_videos.previous_page_number }}</a></li>
  {% else %}
      <li class="page-item disabled"><a class="page-link" href="?page=#">上一页</a></li>
  {% endif %}
  <!-- 显示当前页面信息 -->
    <li class="page-item active"><a class="page-link" >{{ all_videos.number }}</a></li>
  <!-- 如果当前页还有下一页，显示一个下一页的按钮 -->
  {% if all_videos.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ all_videos.next_page_number }}" >{{ all_videos.next_page_number }}</a></li>
      <li class="page-item"><a class="page-link" href="?page={{ all_videos.next_page_number }}">下一页</a></li>
  {% endif %}
        <li class="page-item disabled"><a class="page-link" href="?page=#">找到{{ all_videos.paginator.count }}部电影</a></li>
        <li class="page-item disabled"><a class="page-link" href="?page=#">共有{{ all_videos.paginator.num_pages }}页</a></li>
        </ul>
        

</div>

{% endblock %}

templates/info.html
{% extends "base.html" %}

{% block mainbody %}
             <!-- 选项栏 -->
        <div class="container mt-5">
                <ul class="nav nav-pills">

{#                        <li class="nav-item">#}
{#                            <a class="nav-link active" href="/info/">#}
{#                                用户信息#}
{#                            </a>#}
{#                        </li>#}
{#                        <li class="nav-item">#}
{#                            <a class="nav-link" href="/info_fav/">#}
{#                                收藏#}
{#                            </a>#}
{#                        </li>#}
{#                        <li class="nav-item">#}
{#                            <a class="nav-link" href="/message/">#}
{#                                信息#}
{#                            </a>#}
{#                        </li>#}

                    </ul>
        </div>
         <!-- 内容栏 -->
		<div class="container mt-5">

			<div>
				<table class="table">
					<tbody>
						<tr>
							<td>
								<div>
									<div class="my-5">
										<img style="height:150px;width:150px;" src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1531299560276&di=62f72a38ccc8c4f0e1cb2fd7cdf01a54&imgtype=0&src=http%3A%2F%2Fimages6.fanpop.com%2Fimage%2Fphotos%2F40700000%2FMinions-despicable-me-minions-40777745-320-320.gif" class="rounded-circle ">
									</div>
{#									<button class="btn btn-success" type="submit">#}
{#										更改头像#}
{#									</button>#}
								</div>
							</td>
							<td>
								<div class="my-5">
									<div class="input-group mb-3">
										<div class="input-group-prepend">
											<span class="input-group-text" id="basic-addon1">
												昵称
											</span>
										</div>
										<input type="text" class="form-control" placeholder="{{ request.user.nick_name }}" aria-label="Username"
										aria-describedby="basic-addon1">
									</div>
									<div class="input-group mb-3">
										<div class="input-group-prepend">
											<span class="input-group-text" id="basic-addon1">
												联系方式
											</span>
										</div>
										<input type="text" class="form-control" placeholder="{{ request.user.mobile }}" aria-label="Phone"
										aria-describedby="basic-addon1">
									</div>
									<div class="input-group mb-3">
										<div class="input-group-prepend">
											<span class="input-group-text" id="basic-addon1">
												邮箱
											</span>
										</div>
										<input type="text" class="form-control" placeholder="{{ request.user.email }}" aria-label="Email"
										aria-describedby="basic-addon1">
									</div>
{#									<button class="btn btn-success" style="float: right;" type="submit">#}
{#										保存#}
{#									</button>#}
								</div>
							</td>
						</tr>
				</table>
			</div>
		</div>
{% endblock %}

templates/test.html
{{ res }}
{% for r in res %}
    {{ r.email }}
{% endfor %}